sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

# Set the default environment.
env:
  global:
    - WSU_GRUNT=0
    - WP_VERSION=latest
    - WP_MULTISITE=1

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_pull_requests: true
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS

branches:
  only:
    - master

matrix:
  include:
    - php: 7.1
      env: WP_MULTISITE=0
    - php: 7.0
      env: WSU_GRUNT=1
    - php: 5.6
      env: WP_VERSION=nightly

before_script:
    - phpenv config-rm xdebug.ini
    - composer config --list --global
    - export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    - |
      # Install the specified version of PHPUnit depending on the PHP version:
      case "$TRAVIS_PHP_VERSION" in
        7.1|7.0)
          echo "Using PHPUnit 5.7"
          composer global require "phpunit/phpunit=5.7.*"
          ;;
        5.6|5.5|5.4|5.3)
          echo "Using PHPUnit 4.8"
          composer global require "phpunit/phpunit=4.8.*"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - |
      if [[ "$WSU_GRUNT" == 1 ]]; then
        composer install
        nvm install stable
        npm install -g grunt-cli
        npm install
        npm prune
        npm --version
        node --version
      fi
    - mysql --version
    - phpenv versions
    - php --version

script:
    - phpunit --version
    - phpunit
    - |
      if [[ "$TRAVIS_PHP_VERSION" == 7.0 ]]; then
        grunt --version
        grunt
      fi
